app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_EXPIRATION_MS}
jwt.refreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Admin Seeder
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
