spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sajid
spring.datasource.password=sajid@1584
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging configuration
logging.level.com.hilip.lms=DEBUG

app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_EXPIRATION_MS}
jwt.refreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}

# Admin Seeder
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
